version: "3.7"

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456