version: '3.7'

services:
  blog.server:
    image: ${DOCKER_REGISTRY-}blogserver
    restart: always
    build:
      context: ..
      dockerfile: Blog.Service/Dockerfile
    ports:
      - "8060:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: