version: '3.7'

services:
  blog.server:
    image: ${DOCKER_REGISTRY-}blogserver
    build:
      context: .
      dockerfile: Blog.Server/Dockerfile
    ports:
      - "8060:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456